USE test;
DROP TABLE IF EXISTS `T_REFRIGERATOR`;
CREATE TABLE `T_REFRIGERATOR` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `VALUE` VARCHAR(10) DEFAULT NULL,
  `TIME` DATETIME DEFAULT NULL,
  `STATE` INT(2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

SET FOREIGN_KEY_CHECKS = 1;
